version: '3'
services:
  mysqldb:
    image: mariadb:11.3
    container_name: futsalmatchupdb
    volumes:
      - ./node/config/FutsalMatchUp.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./../../futsaldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: futsalMatchUp
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      SERVICE_TAG: dev
      SERVICE_NAME: mysqldb
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - futsalbackend

  nodeapp:
    container_name: futsalmatchupserver
    build: ./node/
    image: nodeapp:v1
    ports:
      - 3000:3000
    environment:
      HOST: mysqldb
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: futsalMatchUp
      ACCESS_TOKEN_SECRET: 628903f4aeaa823310c3ac26e15b488a03c1b82d63a49611db97561e04f1f4dc879ef12cc31753919a83b190a0c7bea3e8d60b57741b4dc0bcf5c9fe3a0586a6
      REFRESH_TOKEN: 8ac9979eab443c0934a1ed35905880c37e387e4d3ea436c5cb2dae8e83a042d3a7044b7ffdb6d7c096e4ac0e8b811fa0b197fa356e20d391766363f462f8d3d5
    expose:
      - 3000
    depends_on:
      - mysqldb
    networks:
      - futsalbackend
      
networks:
  futsalbackend:
    driver: bridge
