# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

# Update dependancies
# 'cd frontend;' is needed with every action since flutter root dir is in 'futsalmatchup/frontend/'
    - run: cd frontend/; 
           flutter pub get
# Runs the tests
    - run: cd frontend/;
           flutter test
# Builds application in linux env
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - run: cd frontend/;
           flutter config --enable-linux-desktop
    
    - run: cd frontend/;
           flutter build linux

    - run: cd frontend/;
            flutter build linux
